language: python

python:
  - 2.7

env:

  - TOXENV=py27-django111
  - TOXENV=py36-django111

matrix:
  include:
    - python: 2.7
      env: TOXENV=quality

cache:
  - pip

install:
    - pip install -U codecov pip wheel
    - make requirements

script:
  - tox

after_success:
  - codecov

deploy:
    provider: pypi
    user: edx
    password:
         secure: dQKjSK9Tf7VM8SzoYxZy5zsdhOojRG1FNO0IbTvdiDQ2HwtPRwHycAoustFiUqgXxUT4cHdvm1kLlRaf+W4LHMaBqzw3MPuYMETrvS/WghbVx3yzGgMtjffFhd/QgnqX+nP3Q6JE0/NXm7iVGj8TSK0Wu7Vae5OcJe1I4qgHbdU=
    distributions: sdist bdist_wheel
    on:
        tags: true
